import React from 'react';
import { Head, Link } from '@inertiajs/react';
import Navbar from '../../Components/Navbar';
import AgeVerificationModal from '../../Components/AgeVerificationModal';
import { FileText, ShieldCheck, Scale, Lock, ArrowLeft, Download, CheckCircle2 } from 'lucide-react';

export default function TermsOfService() {
    const sections = [
        {
            id: 'membership',
            title: '1. Membership Criteria & Private Access',
            content: `Bordeux AI is an exclusive, invitation-only private wine concierge and AI sommelier service. Access is strictly restricted to verified individuals who are at least 21 years of age (or the legal drinking age in their jurisdiction). Membership tokens are personal, single-use, and non-transferable. You are responsible for maintaining the confidentiality of your account credentials and Telegram synchronization keys.`
        },
        {
            id: 'ai-disclaimer',
            title: '2. AI Sommelier Advisory Disclaimer',
            content: `All wine pairing advice, vintage condition analytics, decanting time estimates, and Parker scale rating predictions generated by Bordeux AI (powered by DeepSeek intelligence) are provided for luxury advisory and culinary enhancement purposes only. While our algorithms achieve exceptional accuracy, secondary market bottle valuations and auction price estimates fluctuate based on market dynamics and bottle storage history.`
        },
        {
            id: 'billing',
            title: '3. High-Ticket S2S Billing & Settlement Terms',
            content: `Memberships are billed on a recurring monthly or annual basis as selected in your Membership Concierge dashboard. Transactions are processed via encrypted Server-to-Server (S2S) merchant gateways (including Ezzygate, Corefy, and Cardaq) with 256-bit signature validation. Annual subscriptions include a 17% fee discount. Subscriptions automatically renew unless cancelled at least 48 hours prior to the billing date.`
        },
        {
            id: 'cellar-data',
            title: '4. Cellar Portfolio Rights & Privacy',
            content: `Members retain 100% ownership of all wine cellar collection data, tasting notes, and personal preference parameters submitted to Bordeux AI. We enforce zero third-party data monetization. Your private cellar holdings and collection valuations remain strictly confidential.`
        },
        {
            id: 'termination',
            title: '5. Conduct & Termination of Service',
            content: `Bordeux AI reserves the right to suspend or terminate membership access immediately without prior notice in the event of unauthorized automated scraping, reverse-engineering of sommelier algorithms, fraudulent payment chargebacks, or violation of our private club code of conduct.`
        },
        {
            id: 'governing-law',
            title: '6. Governing Law & Dispute Resolution',
            content: `These Terms of Service are governed by and construed in accordance with international commercial law. Any disputes or claims arising out of membership or service usage shall be settled through confidential binding arbitration.`
        }
    ];

    return (
        <div className="min-h-screen bg-[#0a0a0a] text-slate-100 flex flex-col font-sans selection:bg-[#4a0e17] selection:text-white">
            <Head title="Terms of Service — Bordeux AI Private Club" />
            <AgeVerificationModal />
            <Navbar />

            <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-12 flex-1 w-full space-y-10">
                {/* Header Banner */}
                <div className="glass-panel-burgundy p-8 sm:p-10 rounded-3xl border border-[#d4af37]/30 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6 shadow-2xl relative overflow-hidden">
                    <div className="space-y-3 relative z-10">
                        <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-[#d4af37]/15 text-[#f3cf65] text-xs font-bold uppercase tracking-widest border border-[#d4af37]/40">
                            <Scale className="w-4 h-4 text-[#d4af37]" />
                            <span>Legal Governance • Version 2.6</span>
                        </div>
                        <h1 className="font-serif-luxury text-3xl sm:text-5xl font-bold text-white tracking-tight">
                            Terms of Service
                        </h1>
                        <p className="text-xs text-slate-300 font-light">
                            Effective Date: January 1, 2026 • Private Club Membership Agreement
                        </p>
                    </div>

                    <Link
                        href={route('home')}
                        className="px-5 py-3 rounded-xl glass-panel text-xs font-bold uppercase tracking-wider text-slate-200 hover:text-white border border-[#d4af37]/30 hover:border-[#d4af37] transition flex items-center space-x-2 relative z-10 shrink-0"
                    >
                        <ArrowLeft className="w-4 h-4 text-[#d4af37]" />
                        <span>Return to Club</span>
                    </Link>
                </div>

                {/* Content Layout */}
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                    {/* Table of Contents */}
                    <div className="lg:col-span-4 space-y-4">
                        <div className="glass-panel p-6 rounded-3xl border border-[#d4af37]/20 sticky top-28 space-y-4">
                            <h3 className="font-serif-luxury text-base font-bold text-white uppercase tracking-wider border-b border-[#d4af37]/15 pb-3">
                                Table of Contents
                            </h3>
                            <nav className="space-y-2 text-xs">
                                {sections.map((s) => (
                                    <a
                                        key={s.id}
                                        href={`#${s.id}`}
                                        className="block p-2 rounded-xl text-slate-400 hover:text-[#f3cf65] hover:bg-[#4a0e17]/30 transition"
                                    >
                                        {s.title}
                                    </a>
                                ))}
                            </nav>
                        </div>
                    </div>

                    {/* Main Legal Clauses */}
                    <div className="lg:col-span-8 space-y-6">
                        {sections.map((s) => (
                            <div
                                key={s.id}
                                id={s.id}
                                className="glass-panel p-8 rounded-3xl border border-[#d4af37]/15 space-y-4 scroll-mt-28 hover:border-[#d4af37]/40 transition"
                            >
                                <h2 className="font-serif-luxury text-xl font-bold text-white flex items-center space-x-2">
                                    <CheckCircle2 className="w-5 h-5 text-[#d4af37] shrink-0" />
                                    <span>{s.title}</span>
                                </h2>
                                <p className="text-slate-300 text-xs sm:text-sm leading-relaxed font-light">
                                    {s.content}
                                </p>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            {/* Footer */}
            <footer className="border-t border-[#d4af37]/10 bg-[#070707] py-8 text-center text-xs text-slate-500">
                <div className="max-w-7xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-4">
                    <p>© 2026 Bordeux AI Concierge. All rights reserved.</p>
                    <div className="flex space-x-6">
                        <Link href={route('legal.terms')} className="text-[#d4af37] font-semibold">Terms of Service</Link>
                        <Link href={route('legal.privacy')} className="hover:text-[#d4af37] transition">Privacy Policy</Link>
                        <Link href={route('legal.refund')} className="hover:text-[#d4af37] transition">Refund Policy</Link>
                    </div>
                </div>
            </footer>
        </div>
    );
}
